## About iPython Notebooks ##

iPython Notebooks are interactive coding environments embedded in a webpage. You will be using iPython notebooks in this class. Make sure you fill in any place that says `# BEGIN CODE HERE #END CODE HERE`. After writing your code, you can run the cell by either pressing "SHIFT"+"ENTER" or by clicking on "Run" (denoted by a play symbol). Before you turn this problem in, make sure everything runs as expected. First, **restart the kernel** (in the menubar, select Kernel$\rightarrow$Restart) and then **run all cells** (in the menubar, select Cell$\rightarrow$Run All). 

 **What you need to remember:**

- Run your cells using SHIFT+ENTER (or "Run cell")
- Write code in the designated areas using Python 3 only
- Do not modify the code outside of the designated areas
- In some cases you will also need to explain the results. There will also be designated areas for that. 

Fill in your **NAME** and **AEM** below:

In [1]:
NAME = "Sotiris Ftiakas"
AEM = "3076"

---

# Assignment 1 - Linear Models #

Welcome to your first assignment. This exercise gives you a brief introduction to Python and the fundamental libraries for machine learning. It also gives you a wide understanding on how linear models work.

After this assignment you will:
- Be able to use iPython Notebooks
- Be able to use numpy and pandas functions
- Be able to build your first linear model from scratch
- Be able to use the basic functions of scikit-learn

**Exercise**: Set test to `"Hello World"` in the cell below to print "Hello World" and run the two cells below.

In [2]:
# BEGIN CODE HERE
test = "Hello World"

#END CODE HERE

In [3]:
print ("test: " + test)

test: Hello World

**Expected output**:
test: Hello World

## 1. Numpy & Pandas ##

The [**NumPy**](https://numpy.org/) library is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. 

The [**Pandas**](https://pandas.pydata.org/) library is built on NumPy and provides easy-to-use data structures and data analysis tools for the Python programming language.

Feel free to look at the documentation ([NumPy Doc](https://numpy.org/doc/1.18/user/quickstart.html) & [Pandas Doc](https://pandas.pydata.org/docs/)) of those libraries troughout this assignment. 

As a convention we always import the libraries as follows:

In [4]:
# Run this cell
import numpy as np
import pandas as pd

### 1.1 The very basic of NumPy ###

**1.1.1 Exercise**: Create an 2-dimensional *NumPy* array (2x3) which contains the numbers 1-6.

In [5]:
# BEGIN CODE HERE
a = np.array([[1,2,3],[4,5,6]])

#END CODE HERE

In [6]:
print(a)

[[1 2 3]
 [4 5 6]]

**Expected output:** [[1 2 3][4 5 6]]

**1.1.2 Exercise**: Set the variable **el** with the 2nd element of the 2nd row of the array *a* and the variable **col** as the 2nd column. *Tip: Use slicing*

In [7]:
# BEGIN CODE HERE
el = a[1][1]
col = a[0:2,1]

#END CODE HERE

In [8]:
print("el:" + str(el))
print("col:" + str(col))

el:5
col:[2 5]

**Expected output:** 
<table>
    <tr> 
        <td> el: </td> 
        <td> 5 </td>
    </tr>
    <tr>
    <td> col: </td> 
    <td> [2,5] </td>
    </tr>
</table>

**1.1.3 Exercise**: Create a 3x4 array full of zeros, create an 4x5 array full of ones and 2x3 array full of random values (0 to 10) using the fucntions np.zeros, np.ones, and np.random.random accordingly.

In [9]:
np.random.seed(42)
# BEGIN CODE HERE
zero_array =  np.zeros( (3,4) )
one_array = np.ones( (4,5) )
random_array = np.random.random( (2,3) )

#END CODE HERE

In [10]:
print("zero_array:" + str(zero_array))
print("one_array:" + str(one_array))
print("random_array:" + str(random_array))

zero_array:[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
one_array:[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
random_array:[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]]

Two common numpy functions used are [np.shape](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.shape.html) and [np.reshape()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html). 
- X.shape is used to get the shape (dimension) of a matrix/vector X. 
- X.reshape(...) is used to reshape X into some other dimension.

**1.1.4 Exercise**: Implement the function **custom_reshape** that takes an input of shape (length, height, depth) and returns a vector of shape (length\*height\*depth, 1).

In [11]:
def custom_reshape(my_array):
    """
    Argument:
    my_array -- a numpy array of shape (length, height, depth)
    
    Returns:
    v -- a vector of shape (length*height*depth, 1)
    """
    # BEGIN CODE HERE

    c=0
    v= np.empty( (my_array.shape[0]*my_array.shape[1]*my_array.shape[2],1) )
    
    for l in range (my_array.shape[0]):
        for h in range (my_array.shape[1]):
            for d in range (my_array.shape[2]):
                v[c][0]=my_array[l][h][d]
                c+=1

    #END CODE HERE

    return v

In [12]:
# This is a 3 by 3 by 2 array.
my_array = np.array([[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])

print ("custon_reshape(my_array) = " + str(custom_reshape(my_array)))

custon_reshape(my_array) = [[0.67826139]
 [0.29380381]
 [0.90714982]
 [0.52835647]
 [0.4215251 ]
 [0.45017551]
 [0.92814219]
 [0.96677647]
 [0.85304703]
 [0.52351845]
 [0.19981397]
 [0.27417313]
 [0.60659855]
 [0.00533165]
 [0.10820313]
 [0.49978937]
 [0.34144279]
 [0.94630077]]

**Expected Output**: 


<table>
     <tr> 
       <td> custon_reshape(my_array) </td> 
       <td> [[ 0.67826139]
 [ 0.29380381]
 [ 0.90714982]
 [ 0.52835647]
 [ 0.4215251 ]
 [ 0.45017551]
 [ 0.92814219]
 [ 0.96677647]
 [ 0.85304703]
 [ 0.52351845]
 [ 0.19981397]
 [ 0.27417313]
 [ 0.60659855]
 [ 0.00533165]
 [ 0.10820313]
 [ 0.49978937]
 [ 0.34144279]
 [ 0.94630077]]</td> 
     </tr>
    
   
</table>

**1.1.5 Exercise**: Create an array of 50 evenly spaced values from 0 to 3 using the np.linspace() function

In [13]:
# BEGIN CODE HERE
x = np.linspace(0,3,50)

#END CODE HERE

In [14]:
print ("x: " + str(x))

x: [0.         0.06122449 0.12244898 0.18367347 0.24489796 0.30612245
 0.36734694 0.42857143 0.48979592 0.55102041 0.6122449  0.67346939
 0.73469388 0.79591837 0.85714286 0.91836735 0.97959184 1.04081633
 1.10204082 1.16326531 1.2244898  1.28571429 1.34693878 1.40816327
 1.46938776 1.53061224 1.59183673 1.65306122 1.71428571 1.7755102
 1.83673469 1.89795918 1.95918367 2.02040816 2.08163265 2.14285714
 2.20408163 2.26530612 2.32653061 2.3877551  2.44897959 2.51020408
 2.57142857 2.63265306 2.69387755 2.75510204 2.81632653 2.87755102
 2.93877551 3.        ]

**1.1.6 Exercise**: Draw 20 random samples from a multivariate normal distribution using the [numpy.random.multivariate_normal](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.random.multivariate_normal.html#numpy.random.multivariate_normal). Use the parameters given

In [15]:
np.random.seed(42)
num_observations = 20
mean = [0, 0]
cov = [[1, 0], [0, 100]]

# BEGIN CODE HERE
multi = np.random.multivariate_normal(mean,cov,num_observations)


#END CODE HERE

In [16]:
print ("x: " + str(multi))

x: [[ -0.1382643    4.96714153]
 [  1.52302986   6.47688538]
 [ -0.23413696  -2.34153375]
 [  0.76743473  15.79212816]
 [  0.54256004  -4.69474386]
 [ -0.46572975  -4.63417693]
 [ -1.91328024   2.41962272]
 [ -0.56228753 -17.24917833]
 [  0.31424733 -10.1283112 ]
 [ -1.4123037   -9.08024076]
 [ -0.2257763   14.65648769]
 [ -1.42474819   0.67528205]
 [  0.11092259  -5.44382725]
 [  0.37569802 -11.50993577]
 [ -0.29169375  -6.0063869 ]
 [  1.85227818  -6.01706612]
 [ -1.05771093  -0.13497225]
 [ -1.22084365   8.22544912]
 [ -1.95967012   2.08863595]
 [  0.19686124 -13.28186049]]

**1.1.7 Exercise**: Change the *?* so as the scatter plot to show the values of the *multi* variable

In [17]:
# Run this block to see a visual represntation of your samples.
import matplotlib.pyplot as plt
plt.figure(figsize=(8,8))
# BEGIN CODE HERE
plt.scatter(multi[0:num_observations, 0], 
            multi[0:num_observations, 1],
            c = 'r', alpha = .4)
#END CODE HERE

### 1.2 The very basic of Pandas ###

- Read & Write CSV
- iloc, loc, and slices
- Merge & concatenate

**1.2.1 Exercise:** Read the file input1.csv into a dataframe using the pandas read_csv() function. Set the 1st row as the names of the columns.

In [18]:
# BEGIN CODE HERE
df1 = pd.read_csv("input1.csv")


#END CODE HERE

In [19]:
df1.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

**1.2.2 Exercise:** Find the mean value of the *trestbps* variable.

In [20]:
# BEGIN CODE HERE
mean_trestbps = df1["trestbps"].mean()

#END CODE HERE

In [21]:
print("Average:" + str(mean_trestbps) )

Average:128.77

**1.2.3 Exercise:** Read the file input2.csv into a dataframe using the pandas read_csv() function and concatenate it with df1 using pd.concat().

In [22]:
# BEGIN CODE HERE
df2 = pd.read_csv("input2.csv")
df2.columns=df1.columns

df = pd.concat([df1,df2])

#END CODE HERE

In [23]:
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
5,57,1,0,140,192,0,1,148,0,0.4,1,0,1,1
6,56,0,1,140,294,0,0,153,0,1.3,1,0,2,1
7,44,1,1,120,263,0,1,173,0,0.0,2,0,3,1
8,52,1,2,172,199,1,1,162,0,0.5,2,0,3,1
9,57,1,2,150,168,0,1,174,0,1.6,2,0,2,1
10,54,1,0,140,239,0,1,160,0,1.2,2,0,2,1
11,48,0,2,130,275,0,1,139,0,0.2,2,0,2,1
12,49,1,1,130,266,0,1,171,0,0.6,2,0,2,1
13,64,1,3,110,211,0,0,144,1,1.8,1,0,2,1
14,58,0,3,150,283,1,0,162,0,1.0,2,0,2,1
15,50,0,2,120,219,0,1,158,0,1.6,1,0,2,1
16,58,0,2,120,340,0,1,172,0,0.0,2,0,2,1
17,66,0,3,150,226,0,1,114,0,2.6,0,0,2,1
18,43,1,0,150,247,0,1,171,0,1.5,2,0,2,1
19,69,0,3,140,239,0,1,151,0,1.8,2,2,2,1
20,59,1,0,135,234,0,1,161,0,0.5,1,0,3,1
21,44,1,2,130,233,0,1,179,1,0.4,2,0,2,1
22,42,1,0,140,226,0,1,178,0,0.0,2,0,2,1
23,61,1,2,150,243,1,1,137,1,1.0,1,0,2,1
24,40,1,3,140,199,0,1,178,1,1.4,2,0,3,1
25,71,0,1,160,302,0,1,162,0,0.4,2,2,2,1
26,59,1,2,150,212,1,1,157,0,1.6,2,0,2,1
27,51,1,2,110,175,0,1,123,0,0.6,2,0,2,1
28,65,0,2,140,417,1,0,157,0,0.8,2,1,2,1
29,53,1,2,130,197,1,0,152,0,1.2,0,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172,58,1,0,100,234,0,1,156,0,0.1,2,1,3,0
173,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
174,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
175,58,1,0,146,218,0,1,105,0,2.0,1,1,3,0
176,57,1,1,124,261,0,1,141,0,0.3,2,0,3,0
177,58,0,1,136,319,1,0,152,0,0.0,2,2,2,0
178,61,1,0,138,166,0,0,125,1,3.6,1,1,2,0
179,42,1,0,136,315,0,1,125,1,1.8,1,0,1,0
180,52,1,0,128,204,1,1,156,1,1.0,1,0,0,0
181,59,1,2,126,218,1,1,134,0,2.2,1,1,1,0
182,40,1,0,152,223,0,1,181,0,0.0,2,0,3,0
183,61,1,0,140,207,0,0,138,1,1.9,2,1,3,0
184,46,1,0,140,311,0,1,120,1,1.8,1,2,3,0
185,59,1,3,134,204,0,1,162,0,0.8,2,2,2,0
186,57,1,1,154,232,0,0,164,0,0.0,2,1,2,0
187,57,1,0,110,335,0,1,143,1,3.0,1,1,3,0
188,55,0,0,128,205,0,2,130,1,2.0,1,1,3,0
189,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
190,58,1,0,114,318,0,2,140,0,4.4,0,3,1,0
191,58,0,0,170,225,1,0,146,1,2.8,1,2,1,0
192,67,1,2,152,212,0,0,150,0,0.8,1,0,3,0
193,44,1,0,120,169,0,1,144,1,2.8,0,0,1,0
194,63,1,0,140,187,0,0,144,1,4.0,2,2,3,0
195,63,0,0,124,197,0,1,136,1,0.0,1,0,2,0
196,59,1,0,164,176,1,0,90,0,1.0,1,2,1,0
197,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
198,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
199,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
200,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
201,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

**1.2.4 Exercise:** Select the rows where *chol*>200 and only the columns age, sex, cp, chol, target.

In [24]:
# BEGIN CODE HERE

selected = df.loc[df["chol"] >200]
selected = selected[['age','sex','cp','chol','target']]

#END CODE HERE

In [25]:
selected

     age  sex  cp  chol  target
0     63    1   3   233       1
1     37    1   2   250       1
2     41    0   1   204       1
3     56    1   1   236       1
4     57    0   0   354       1
6     56    0   1   294       1
7     44    1   1   263       1
10    54    1   0   239       1
11    48    0   2   275       1
12    49    1   1   266       1
13    64    1   3   211       1
14    58    0   3   283       1
15    50    0   2   219       1
16    58    0   2   340       1
17    66    0   3   226       1
18    43    1   0   247       1
19    69    0   3   239       1
20    59    1   0   234       1
21    44    1   2   233       1
22    42    1   0   226       1
23    61    1   2   243       1
25    71    0   1   302       1
26    59    1   2   212       1
28    65    0   2   417       1
32    44    1   1   219       1
33    54    1   2   273       1
34    51    1   3   213       1
36    54    0   2   304       1
37    54    1   2   232       1
38    65    0   2   269       1
..   ...  ...  ..   ...     ...
164   66    1   0   212       0
165   55    0   0   327       0
167   54    1   0   286       0
168   56    1   0   283       0
169   46    1   0   249       0
170   61    1   3   234       0
171   67    1   0   237       0
172   58    1   0   234       0
173   47    1   0   275       0
174   52    1   0   212       0
175   58    1   0   218       0
176   57    1   1   261       0
177   58    0   1   319       0
179   42    1   0   315       0
180   52    1   0   204       0
181   59    1   2   218       0
182   40    1   0   223       0
183   61    1   0   207       0
184   46    1   0   311       0
185   59    1   3   204       0
186   57    1   1   232       0
187   57    1   0   335       0
188   55    0   0   205       0
189   61    1   0   203       0
190   58    1   0   318       0
191   58    0   0   225       0
192   67    1   2   212       0
197   57    0   0   241       0
198   45    1   3   264       0
201   57    0   1   236       0

[251 rows x 5 columns]

## 2.0 Linear Models ##

In this part of the excersice you are going to build a logistic regression model from scratch.

**2.1 Exercise:** Implement the sigmoid function using numpy. 

sigmoid function:
$$\sigma(t)= \dfrac{1}{1 + exp(-t)}$$

In [47]:
def sigmoid(x):
    """
    Compute the sigmoid of x

    Arguments:
    x -- A numpy array of any size

    Return:
    s -- sigmoid(x)
    """
    # BEGIN CODE HERE
    s = 1/(1+np.exp(-x))
    
    #END CODE HERE
    
    return s

In [48]:
x = np.array([2, 3, 4])
print(sigmoid(x))

[0.88079708 0.95257413 0.98201379]

**2.2 Exercise**: Implement parameter initialization in the cell below. You have to initialize w (weight vector) and b (bias) with zeros.

In [52]:
def initialize(dim):
    """  
    Argument:
    dim -- the number of parameters

    Returns:
    w -- initialized vector of shape (dim, 1)
    b -- initialized scalar
    """
    # BEGIN CODE HERE
    w = np.zeros( (1,dim) )
    b = 0
    
    #END CODE HERE

    assert(w.shape == (1, dim))
    assert(isinstance(b, float) or isinstance(b, int))

    return w,b

In [54]:
dim = 5
w, b = initialize(dim)
print ("w = " + str(w))
print ("b = " + str(b))

w = [[0. 0. 0. 0. 0.]]
b = 0

**2.3 Exercise**: Compute the cost of logistic regression using the sigmoid function above. You can find the dot product of two arrays by using the [numpy.dot()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html)

In [150]:
def compute_cost(w,b,X,Y):
    """
    Arguments:
    w -- weights
    b -- bias
    X -- input data
    Y -- target or label vector

    Return:
    sigma -- the sigmoid of the z
    cost -- cost for logistic regression
    """
    # BEGIN CODE HERE
    
    sum=0
    c=0
    sigma = np.zeros(Y.shape[1])
    for i in range (Y.shape[1]):
        sig = sigmoid(b + np.dot(w,X[i]))
        sum+= (Y[0][i]*np.log(sig) + ((1-Y[0][i])*np.log(1-sig)))
        sigma[c]=sig
        c+=1
    
    sum*=(-1/Y.shape[1])
    
    cost = sum

    #END CODE HERE

    return sigma, cost

In [152]:
w, b, X, Y = np.array([1.,2.]), 2., np.array([[1.,3.],[2.,4.],[-1.,-3.2]]), np.array([[1,0,1]])
sigma, cost = compute_cost(w, b, X, Y)
print("Sigmoid:" + str(sigma))
print("Cost:" + str(cost))

Sigmoid:[0.99987661 0.99999386 0.00449627]
Cost:5.801545319394553

**Expected Output**:

<table style="width:50%">
 <tr>
 <td>Sigmoid </td> <td> [0.99987661 0.99999386 0.00449627] </td>
 </td> </tr>
 <tr>
        <td>  cost:  </td>
        <td> 5.801545319394553 </td>
    </tr>

</table>

**2.4 Exercise** Compute the gradient of w and b.

In [224]:
def gradient(w,b,X,Y,sigma):
    """
    Arguments:
    w -- weights
    b -- bias
    X -- input data
    Y -- target or label vector

    Return:
    dw, db -- gradient of the loss with respect to w, gradient of the loss with respect to b
    """
    # BEGIN CODE HERE
    
    #I find the db here
    
    sum=0

    for i in range (Y.shape[1]):      
        sum+=(sigma[i]-Y[0][i])*1
        
    sum*=(1/Y.shape[1])
    newb = b-sum
    
    db = b-newb
    
    #I find the dw here
    
    dw=np.zeros((1,w.shape[0]))
    for j in range (w.shape[0]):
        sum=0
        for i in range (Y.shape[1]):
            sum+=(sigma[i]-Y[0][i])*X[i][j]
            
        sum*=(1/Y.shape[1])
        neww=w[j]-sum
        dw[0][j]= w[j]-neww
            

    #END CODE HERE

    return dw, db

In [225]:
w, b, X, Y = np.array([1.,2.]), 2., np.array([[1.,3.],[2.,4.],[-1.,-3.2]]), np.array([[1,0,1]])
dw, db = gradient(w, b, X, Y,sigma)
print ("dw = " + str(dw))
print ("db = " + str(db))

dw = [[0.99845601 2.39507239]]
db = 0.001455578136784208

**Expected Output**:

<table style="width:50%">
    <tr>
        <td>  dw  </td>
      <td> [[0.99845601, 2.39507239]]</td>
    </tr>
    <tr>
        <td>  db  </td>
        <td> 0.001455578136784208 </td>
    </tr>

**2.5 Exercise** Implement the parameters update function below. The goal is to learn $w$ and $b$ by minimizing the cost function $J$. For a parameter $\theta$, the update rule is $ \theta = \theta - \alpha \text{ } d\theta$, where $\alpha$ is the learning rate. Tip: Use the functions developed above.

In [ ]:
def update_parameters(w,b,X,Y,num_iterations,learning_rate):
    """
    This function optimizes w and b by running a gradient descent algorithm

      Arguments:
      w -- weights
      b -- bias
      X -- input data
      Y -- target or label vector
      num_iterations -- number of iterations of the optimization loop
      learning_rate -- learning rate of the gradient descent update rule

      Returns:
      params -- dictionary containing the weights w and bias b
      grads -- dictionary containing the gradients of the weights and bias with respect to the cost function.
    """
    for i in range(num_iterations):
        w_prev = w
        b_prev = b
        # BEGIN CODE HERE
        # Cost and gradient calculation
        sigma, cost = 0,0
        dw, db = 0,0
        # update rule
        w = ""
        b = ""
        
        #END CODE HERE


        # Print the cost every 100 training iterations
        if i % 100 == 0:
            print ("Cost after iteration %i: %f" %(i, cost)) 

    return w,b,dw,db

In [ ]:
w, b, X, Y = np.array([1.,2.]), 2., np.array([[1.,3.],[2.,4.],[-1.,-3.2]]), np.array([[1,0,1]])
w,b,dw,db = update_parameters(w, b, X, Y, num_iterations= 100, learning_rate = 0.009)

print ("w = " + str(w))
print ("b = " + str(b))
print ("dw = " + str(dw))
print ("db = " + str(db))

**Expected Output**: 

<table style="width:40%">
<tr>
<td> w </td>
<td>[[ 0.19033591,0.12259159]] </td>
</tr>
<tr>
       <td> b </td>
       <td> 1.92535983008 </td>
    </tr>
    <tr>
       <td> dw </td>
       <td> [[ 0.67752042, 1.41625495]] </td>
    </tr>
    <tr>
       <td> db </td>
       <td> 0.219194504541 </td>
    </tr>

</table>

**2.6 Predict** Implement the predict() function by calculating the $y'$ and then convert the probabilities to actual predictions 0 or 1.

In [ ]:
def predict(w, b, X):
    '''
    Predict whether the label is 0 or 1 using learned logistic regression parameters (w, b)
    
    Arguments:
    w -- weights
    b -- bias, a scalar
    X -- input data
    
    Returns:
    Y_prediction -- a numpy array (vector) containing all predictions (0/1) for the examples in X
    '''

    m = X.shape[0]
    Y_prediction = np.zeros((1,m))
    
    # BEGIN CODE HERE
    # Compute vector "sigma" predicting the probabilities of input X
    sigma = ""
    # Convert probabilities sigma[0,i] to actual predictions.

    #END CODE HERE

    
    assert(Y_prediction.shape == (1, m))
    
    return Y_prediction

In [ ]:
w = np.array([[0.1124579,0.23106775]])
b = -0.3
X = np.array([[1.,1.2],[-1.1,2.],[-3.2,0.1]])
print ("predictions = " + str(predict(w, b, X)))

**Expected Output**: 

<table style="width:30%">
    <tr>
         <td>
             predictions
         </td>
          <td>
            [[1. 1. 0.]]
         </td>  
   </tr>

</table>

**2.7 Exercise** Put all the above blocks in the right order to create a model in the function below.

In [ ]:
def model(X_train, Y_train, X_test, Y_test, num_iterations = 2000, learning_rate = 0.5):
    """
    Builds the logistic regression model by calling the function you've implemented previously

    Arguments:
    X_train -- training set represented by a numpy array
    Y_train -- training labels represented by a numpy array (vector) of shape (1, m_train)
    X_test -- test set represented by a numpy array of shape
    Y_test -- test labels represented by a numpy array (vector) of shape (1, m_test)
    num_iterations -- hyperparameter representing the number of iterations to optimize the parameters
    learning_rate -- hyperparameter representing the learning rate used in the update rule of update_parameters()

    Returns:
    d -- dictionary containing information about the model.
    """
    # BEGIN CODE HERE

    # initialize parameters
    w, b = "",""
    
    # Gradient descent
    w,b,dw,db = "","","",""
    
    # Predict test/train set examples
    Y_prediction_test = ""
    Y_prediction_train = ""

    #END CODE HERE

    # Print train/test Errors
    print("train accuracy: {} %".format(100 - np.mean(np.abs(Y_prediction_train - Y_train)) * 100))
    print("test accuracy: {} %".format(100 - np.mean(np.abs(Y_prediction_test - Y_test)) * 100))


    d = {"Y_prediction_test": Y_prediction_test, 
        "Y_prediction_train" : Y_prediction_train, 
        "w" : w, 
        "b" : b,
        "learning_rate" : learning_rate,
        "num_iterations": num_iterations}

    return d

**2.8 Exercise** Create your own dataset from a multivariate normal distribution to test the model with a total of 2000 samples. The mean and covariance matrix are given for each class.

In [ ]:
import matplotlib.pyplot as plt
num_observations = 1000 #number of observations of each 
mean_class1 = [0,0]
mean_class2 = [1, 4]
cov_matrix =  [[0.5, 0],[0, 0.5]]

# BEGIN CODE HERE
x1 = ""
x2 = ""

# TIP: check numpy vstack and hstack
X = "" #Combine features together
y = "" #Create the labels

#END CODE HERE


plt.figure(figsize=(8,8))
plt.scatter(X[0:num_observations, 0], 
            X[0:num_observations, 1],
            c = 'r', alpha = .4)
plt.scatter(X[num_observations:, 0], 
            X[num_observations:, 1],
            c = 'b', alpha = .4)

Your plot should look like similar to this:

![plot](https://raw.githubusercontent.com/sakrifor/public/master/machine_learning_course/images/plot.png)

**2.9 Exercise** Split your dataset into train and test set and then use the model function to evaluate your model. Be careful to include both classes in train and test set. Finally, make a plot containing the samples and the line the model has learned.

In [ ]:
# BEGIN CODE HERE
X_train, X_test =  "",""
y_train, y_test =  "",""

#END CODE HERE

d = model(X_train,y_train,X_test,y_test,num_iterations = 2000, learning_rate = 0.004)

# Plot again
plt.figure(figsize=(8,8))
plt.scatter(X[0:num_observations, 0], 
            X[0:num_observations, 1],
            c = 'r', alpha = .4)
plt.scatter(X[num_observations:, 0], 
            X[num_observations:, 1],
            c = 'b', alpha = .4)

x_boundary = np.linspace(-3, 4, 1000) # Return evenly spaced numbers over a specified interval.
weights =  d['w'][0]
# BEGIN CODE HERE
y_boundary = ""  # y = -(ax/c + b/c)
#END CODE HERE


plt.plot(x_boundary, y_boundary, color='black')

Your plot should look like similar to this:

![plot](https://raw.githubusercontent.com/sakrifor/public/master/machine_learning_course/images/plot_line.png)

## 3.0 Regularization ##

Rewrite any of the above functions in the below block so as the Logistic Regression to have the option to run with **L1** and **L2** regularization. Rewrite only the functions needed.

In [ ]:
#END CODE HERE

## **Questions** ##

Answer below!

1. Your model should achieve around 93% accuracy in the test set. If you want to improve the accuracy what changes you should make? Report the changes and the results.
2. Besides using a specific number of iterations for your model what else you can do to stop the training? 
3. Do you notice any differences when using the L1 or L2 regularization? Is so, why? If not, why?

Bonus Question:
*What parts of this assignment were not clear or misleading? Are there any other comments on this assignment?*

YOUR ANSWER HERE